
[Config]
default_theme = "THEME_MODERN"
security_flags = []
default_win_console_size = [
1280.0,
720.0,
]

[Metadata]
cs_title = "Coresploit v1.3 Stable"
cs_version = "v1.3 Stable"
title = "Coresploit Configuration"

